src/components/common/Heading.tsx, src/pages/SchedulePage.tsx, src/styles/common/Heading.style.ts
- Heading 컴포넌트 생성
- size 뿐 아니라 maxWidth : 최대 가로 너비 (number)
- noOfLine : 특정 줄 수 이후 maxWidth를 넘어가면 말줄임표(...) 생성
noOfLine = 2, maxWidth = 70px 예시
=> Feature/#1 Heading 컴포넌트 생성

src/hooks/usePopup.tsx, src/pages/SchedulePage.tsx, src/styles/common/Modal.style.ts, src/styles/common/Popup.style.ts
- 모달 box-shadow 옵션을 잘못 적어놔서 수정했습니다.
- 팝업 사용가능한 usePopup 컴포넌트를 만들었습니다.
- 현재 디자인으로 나온 팝업 형태가 천차만별이라서 정말 popup으로 뭔가를 띄울 수 있는 기능만 넣었습니다. 개별적인 컴포넌트를 개발할 때 hook을 사용해 children 끼워넣는 형태로 사용하면 될 것 같습니다.
=> Feature/#1 팝업 사용할 수 있는 usePopup 컴포넌트 생성

src/styles/common/SearchInput.style.ts
- Search Input의 focus 전 잘못 구현된 border color 수정
=> fix(#3) : Search Input의 잘못 구현된 border color 수정

src/assets/data/locations.ts, src/components/mytrip/SearchNotFounded.tsx, src/components/mytrip/SearchResult.tsx, src/components/mytrip/SearchResultItem.tsx, src/components/mytrip/SearchedLocations.tsx, src/hooks/useSearchInput.tsx, src/pages/MyTripCreatePage.tsx, src/recoil/mytrip/selectedLocations.ts, src/styles/mytrip/SearchNotFounded.style.ts, src/styles/mytrip/SearchResultItem.style.ts, src/styles/mytrip/SearchedLocations.style.ts
- 기본 custom hook중 검색 Input의 버그 수정 및 기능 추가 했습니다
- 지역 검색 및 선택 페이지 생성 및 기능 구현
- 검색Input에 onChange 기능이 없어서 추가하면서, 입력시 첫번째 입력이 무시 및 focus가 벗어나는 버그를 수정 했습니다
=> Feature/#24 여행계획 생성간 지역 검색 및 선택 페이지 생성

src/components/common/BottomNavBar/index.tsx, src/components/common/BottomNavBar/style.ts, src/components/home/journals/Journals/index.tsx, src/components/home/journals/Journals/style.ts, src/components/home/journals/shortform/ShortForm/index.tsx, src/components/home/journals/shortform/ShortForm/style.ts, src/components/home/journals/shortform/ShortFormList/index.tsx, src/components/home/journals/shortform/ShortFormList/style.ts, src/components/home/journals/snapshot/SnapshotList/index.tsx, src/components/home/journals/snapshot/SnapshotList/style.ts, src/components/journal/Comment/index.tsx, src/components/journal/CommentItem/index.tsx, src/pages/home/HomePage/index.tsx, src/pages/home/HomePage/style.ts, src/pages/journal/ShortformPage/index.tsx, src/pages/journal/ShortformPage/style.ts, src/router.tsx
- 관련이슈: #55 
- 숏폼 리스트
- 숏폼 페이지
- 스냅사진 리스트
- 카테고리 선택 버튼
=> Feature/#55 숏폼 리스트, 숏폼페이지, 스냅사진 리스트 UI 구현

package-lock.json, package.json, src/components/common/BottomNavBar/index.tsx, src/components/home/journals/Journals/index.tsx, src/components/home/journals/shortform/ShortForm/index.tsx, src/components/home/journals/shortform/ShortForm/style.ts, src/components/home/journals/snapshot/SnapshotList/index.tsx, src/components/home/journals/snapshot/SnapshotList/style.ts, src/components/journal/Comment/style.ts, src/pages/journal/ShortformPage/index.tsx, src/pages/journal/ShortformPage/style.ts, src/pages/journal/SnapshotPage/index.tsx, src/pages/journal/SnapshotPage/style.ts, src/router.tsx
관련 이슈: #55 
- 숏폼 react-youtube 라이브러리 활용하여 다시 만들었습니다. 
- 숏폼 페이지에서 위/아래 스크롤했을 때 현재 보이지 않게 된 영상은 중지되고, 보이게 된 영상이 자동재생됩니다.
- 숏폼페이지 디자인 변경에 따라 BottomNav 수정했습니다.
- 스냅사진 페이지를 만들었습니다.
- 팔로우/팔로잉 컴포넌트(FollowBtn)에 isFollowing=true 줬을 때 디자인이 깨지는데 저만 그런가요??
- 스냅사진 팔로우/팔로잉 버튼 수정
- 북마크 기능 추가
- 각 게시글 케밥메뉴 액션 개발
- 박수 버튼 개발
=> Feature/#55 숏폼 및 스냅사진 여행기 구현

src/assets/data/userpageData.ts, src/components/profile/TripList/index.tsx, src/pages/auth/LoginPage/index.tsx, src/pages/auth/SignUpPage/index.tsx, src/pages/profile/ProfilePage/index.tsx, src/utils/api.ts
관련 이슈: #91
- 로그인 access_token 이 만료되었을때, refresh 토큰을 활용하여 token을 재발급 받고 자동으로 이전 요청을 시작하는 로직 
- refresh 토큰도 만료 되었을 경우, 토큰 삭제 후 login 페이지로 redirect
=> Feature/#91 토큰 만료 핸들링

src/components/common/MenuOptionList/style.ts, src/components/scrapBook/ScrapedTripJournal/index.tsx, src/components/scrapBook/ScrapedTripJournal/style.ts, src/hooks/useConfirm/index.tsx, src/hooks/useConfirm/style.ts, src/hooks/useTextInputPopup/index.tsx, src/hooks/useTextInputPopup/style.ts
관련 이슈: #86 
- 폴더 삭제, 수정 기능 추가
- 유저의 취소/확인을 묻는 useConfirm 팝업 hook 구현
중심적으로 봐 주었으면 하는 부분
- useConfirm 많관부
=> Feature/#86 스크랩 폴더 삭제, 수정

package-lock.json, package.json, src/components/common/PageHeader/index.tsx, src/components/common/PageHeader/style.ts, src/components/home/Recommendation/index.tsx, src/components/home/Recommendation/style.ts, src/components/mytrip/CalendarContainer/index.tsx, src/components/mytrip/CalendarContainer/style.ts, src/components/mytrip/MyLastScheduleCard/index.tsx, src/components/mytrip/MyLastScheduleCard/style.ts, src/pages/ArticlePage/index.tsx, src/pages/auth/SignUpPage/index.tsx, src/pages/auth/SignUpPage/style.ts, src/pages/profile/ProfilePage/index.tsx, src/pages/profile/ProfilePage/style.ts
- 아티클 슬라이드
- 캘린더 날짜 UI
- 모바일 UI 관련 padding 
- Profile page 반응형 디자인
=> Fix#0 자잘한 UI 및 미동작 기능 수정

src/components/common/CommunityPageTemplate/index.tsx, src/components/common/MenuOptionList/index.tsx, src/components/common/MenuOptionList/style.ts, src/components/common/PageTemplate/index.tsx, src/components/common/filterInputs/Filter/index.tsx, src/components/home/journals/Journals/index.tsx, src/components/home/journals/shortform/ShortForm/index.tsx, src/components/home/journals/shortform/ShortForm/style.ts, src/components/home/journals/shortform/ShortFormList/index.tsx, src/components/home/journals/shortform/ShortFormList/style.ts, src/components/journal/Comment/index.tsx, src/components/journal/Comment/style.ts, src/components/journal/CommentItem/index.tsx, src/components/journal/CommentItem/style.ts, src/components/post/BottomNav/index.tsx, src/components/scrapBook/ScrapedTripJournal/index.tsx, src/components/scrapBook/ScrapedTripPlace/index.tsx, src/components/tripDetail/PlanEditMode/index.tsx, src/components/tripDetail/PlanEditMode/style.ts, src/hooks/useAlert/index.tsx, src/hooks/useAlert/style.ts, src/hooks/useReportPopup/index.tsx, src/pages/home/HomePage/index.tsx, src/pages/journal/PostPage/index.tsx, src/pages/journal/ShortformPage/index.tsx, src/pages/journal/ShortformPage/style.ts, src/pages/scrapbook/ScrapBookGroupPage/index.tsx, src/recoil/journals/journalState.ts, src/router.tsx
=> Hotfix/#122 0차 QA 반영

index.html, src/components/article/StationContainer/style.ts, src/components/common/CommunityPageTemplate/style.ts, src/components/common/PageHeader/style.ts, src/components/common/PageTemplate/style.ts, src/components/home/journals/shortform/ShortForm/style.ts, src/components/journal/Comment/style.ts, src/components/scrapBook/ScrapedTripJournal/style.ts, src/hooks/useConfirm/style.ts, src/hooks/useModal/style.ts, src/hooks/useMyTripModal/style.ts, src/hooks/usePopup/style.ts, src/pages/ArticlePage/index.tsx, src/pages/ArticlePage/style.ts, src/pages/PlacePage/index.tsx, src/pages/PlacePage/style.ts, src/pages/journal/ShortformPage/style.ts, src/pages/journal/VideoPage/style.ts, src/pages/mytrip/LocationSearchPage/style.ts, src/pages/mytrip/PlaceCreatePage/style.ts, src/pages/scrapbook/ScrapBookGroupPage/index.tsx, src/router.tsx
Fix/#124 ios safari UI 테스트 및 일부 UI 버그 수정
=> Fix/#124 ios safari UI 테스트 및 일부 UI 버그 수정

src/components/common/PageTemplate/style.ts, src/components/home/journals/shortform/ShortForm/index.tsx, src/components/journal/Comment/index.tsx, src/components/journal/CommentItem/index.tsx, src/components/post/BottomNav/index.tsx, src/pages/ArticlePage/index.tsx
- 아티클과 숏폼 : 댓글과 스크랩 카운트 반영
- ios Safari 반영 테스트 코드
- 댓글창 시간 string format
=> Fix/#124 0.3차 QA

src/components/tripDetail/DayPlan/index.tsx, src/components/tripDetail/DayPlan/style.ts
=> feat(#142): 장소 간 거리 및 점선 UI 구현

src/components/common/TabBar/index.tsx, src/components/home/journals/shortform/ShortForm/index.tsx, src/components/home/journals/shortform/ShortForm/style.ts, src/components/journal/Comment/index.tsx, src/components/journal/Comment/style.ts, src/components/journal/CommentItem/index.tsx, src/hooks/useBodyScrollLock/index.ts, src/hooks/useModal/index.tsx, src/hooks/useModal/style.ts, src/hooks/usePopup/index.tsx, src/hooks/useReportPopup/index.tsx, src/pages/home/HomePage/index.tsx
관련 이슈: #150 
- 숏폼 캡션 구조 수정
- 숏폼 하단부 그라데이션 div 스타일 수정하여 iOS에서 여백 생기는 문제 개선
- 캡션 열었을 때 배경이 까맣게 되도록 수정
- 댓글 Input을 textarea로 변경, 텍스트 길이에 따라 높이 변경됨
- 홈 화면에서 탭 변경 시 path 변경되지 않음 -> 쿼리파라미터로 구현
- iOS Safari에서 modal border-radius 적용되는 지 확인 필요
- 모달 열렸을 때 스크롤 발생되는지 확인 필요
=> Fix/#150 숏폼 및 모달 수정 요구사항 반영

src/components/article/PlaceInfo/index.tsx, src/components/article/PlaceInfo/style.ts, src/components/article/StationContainer/index.tsx, src/components/common/PageHeader/style.ts, src/components/home/ArticleItem/index.tsx, src/components/mytrip/LocationAddItem/style.ts, src/components/post/BottomNav/index.tsx, src/components/post/BottomNav/style.ts, src/components/video/useScrapModal/index.tsx, src/components/video/useScrapModal/style.ts, src/hooks/useModal/style.ts, src/pages/mytrip/PlaceAddPage/index.tsx, src/pages/mytrip/PlaceAddPage/style.ts, src/utils/isLogin.ts
관련 이슈: #153
- 홈 - 아티클 탭 자연스럽게,, 더 많은 threshold 추가
- 아티클 비회원 페이지 기능 관리 ( 로그인 팝업 추가, station href 기능 차단)
- ScrapModal 에서 새폴더 추가 시, 발생하던 새로고침 버그 제거를 위해 새 UI 분리
- 장소 - 내 여행 생성 의 페이지 UI 수정
- x
=> Fix/#153 홈/아티클 QA 수정사항 반영

src/pages/cscenter/FAQDetailPage/index.tsx, src/pages/cscenter/FeedBackPage/index.tsx, src/pages/cscenter/InquiryDetailPage/index.tsx, src/pages/cscenter/InquiryDetailPage/style.ts, src/pages/cscenter/InquiryPage/index.tsx, src/pages/resign/ResignDonePage/style.ts, src/pages/resign/ResignPage/index.tsx, src/pages/resign/ResignPage/style.ts, src/pages/resign/SuggestionContainer/index.tsx, src/pages/resign/SuggestionContainer/style.ts, src/router.tsx
- 관련 이슈: #159 
- 의견 보내기, 문의하기, 탈퇴하기 등 submit 액션 중복 전송 방지
- 내 문의 내역 레이아웃 수정
- 회원 탈퇴 완료 페이지 레이아웃 수정
- 문의하기에서 사진 5개 이상 첨부 시 모달 닫히지 않는 문제 해결
- 프로필 수정>로그아웃 후 로그인 페이지로 navigate 작업이 필요하나 종진님 작업과 겹칠 것 같아 추후 작업하도록 하겠습니다!
=> Fix/#159 2차 QA - 고객지원 서비스, 탈퇴하기 수정 요구사항 반영

src/components/scrapBook/ScrapedTripJournal/index.tsx, src/components/scrapBook/ScrapedTripJournal/style.ts, src/components/scrapBook/ScrapedTripPlace/index.tsx, src/components/scrapBook/ScrapedTripPlace/style.ts, src/pages/scrapbook/ScrapBookGroupPage/index.tsx, src/pages/scrapbook/ScrapBookGroupPage/style.ts, src/pages/scrapbook/ScrapBookPage/index.tsx, src/pages/scrapbook/ScrapBookPage/style.ts
- 여행장소 페이지네이션
- 헤더 고정 / 배경색 추가
- 폴더 이름 줄바꿈
=> Fix/#148 2차 QA 스크랩 페이지 이슈 해결

src/components/mytrip/Calendar/index.tsx, src/components/mytrip/Calendar/style.ts, src/components/mytrip/CalendarContainer/index.tsx, src/components/mytrip/CalendarContainer/style.ts, src/components/mytrip/MyScheduleCard/index.tsx, src/components/tripDetail/LocationHotPlaces/index.tsx, src/components/tripDetail/LocationHotPlaces/style.ts, src/components/tripDetail/LocationRecommendContents/index.tsx, src/components/tripDetail/LocationRecommendContents/style.ts, src/components/tripDetail/SearchPlaces/style.ts, src/components/tripDetail/SelectedPlaces/style.ts, src/hooks/useMyTripModal/style.ts, src/pages/mytrip/LocationSearchPage/index.tsx, src/pages/mytrip/LocationSearchPage/style.ts, src/pages/mytrip/LocationSelectPage/style.ts, src/pages/mytrip/PlaceCreatePage/index.tsx
관련 이슈: #157
- UI 관련 버그 수정
- 캘린더 구현 자체 버그 수정
- 새로운 장소 추가 버그 수정
- ios용 스크롤 css 추가
- ios 스크롤 잘 동작하는지 확인 하기
- 내 여행 홈 UI 관련 논의 후, 수정하기
=> Fix/#157 내 여행 작업

src/components/tripDetail/DayPlan/index.tsx, src/components/tripDetail/DayPlan/style.ts, src/components/tripDetail/EditModeBottomControlBox/style.ts, src/components/tripDetail/EditablePlaceItem/index.tsx, src/components/tripDetail/EditablePlaceItem/style.ts, src/pages/mytrip/DetailPage/style.ts
- 관련 이슈: #164 
- 일정 보기 화면 UI 문제 해결
- 장소 간 거리 클릭 시 경로찾기 이동 구현(Naver 안돼서 GoogleMap으로 함)
- 구글맵 View 수정
- 일정 편집모드 버그 해결
=> Fix/#159 내여행 - 일정보기 UI 수정 사항 반영(지도, 일정변경)

src/assets/types/TUserProfile.ts, src/components/journal/PlaceOperateTime/index.tsx, src/components/tripDetail/SelectedPlaces/index.tsx, src/pages/profile/ProfilePage/index.tsx, src/router.tsx
관련 이슈: #152
- 장소 운영시간 로직 수정
- Profile 정보 가져오는 api 수정
=> Fix/#152 장소 운영시간 로직 수정, Profile 정보 가져오는 api 수정

src/components/tripDetail/MarkerWithInfoWindow/index.tsx, src/components/tripDetail/MarkerWithInfoWindow/style.ts, src/components/tripDetail/PlanMap/index.tsx, src/components/tripDetail/TripPlanList/index.tsx, src/components/tripDetail/TripPlanPlaceItem/index.tsx, src/pages/mytrip/DetailPage/index.tsx
- 관련 이슈: #164 
- 인포윈도우 주소 오류 및 레이아웃 수정
- 지도에서 모든 장소가 보이게 설정
- 포커스 되었을 때 맵 크기 변경
- 마커 간 연결선 날짜별 색상 반영
- 편집모드에서 편집중인 데이터 Map에서 실시간 위치 확인
- 날짜 필터 적용 시 해당 날짜 마커만 보이게 변경
- 드래그 앤 드랍 일정 변경 기능에 오류가 많아 수정 겸 리팩토링 진행할 예정
=> Fix/#164 내 여행 일정 보기 - 지도 관련 이슈 해결

src/utils/api.ts
fix(#157): refresh token 만료 로직 수정
=> fix(#157): refresh token 만료 로직 수정

package-lock.json, package.json, src/components/common/InputContainer/style.ts, src/components/common/TextEditPopupContent/style.ts, src/components/common/filterInputs/extraControllers/BudgetEC/style.ts, src/components/home/journals/shortform/ShortForm/style.ts, src/components/journal/Comment/style.ts, src/components/post/BottomNav/style.ts, src/components/tripDetail/DayPlanEdit/index.tsx, src/components/tripDetail/DayPlanEdit/style.ts, src/components/tripDetail/EditablePlaceItem/index.tsx, src/components/tripDetail/MarkerWithInfoWindow/index.tsx, src/components/tripDetail/PlanEditMode/index.tsx, src/components/tripDetail/PlanEditMode/style.ts, src/components/tripDetail/PlanMap/index.tsx, src/components/tripDetail/TripPlanList/index.tsx, src/components/video/useScrapModal/style.ts, src/hooks/useMyTripModal/style.ts, src/hooks/useTextInputPopup/style.ts, src/pages/cscenter/FeedBackPage/style.ts, src/pages/cscenter/InquiryPage/style.ts, src/pages/mytrip/DetailPage/index.tsx, src/pages/mytrip/MemoPage/style.ts, src/pages/resign/ResignPage/style.ts, src/pages/resign/SuggestionContainer/style.ts
- 관련 이슈: #164 
- iOS에서 input 태그에 포커스 되었을 때 폰트 사이즈 14px 이하일 경우 zoom이 되는 문제를 해결하기 위해 모든 Input, textarea 태그의 폰트사이즈를 16px로 수정하였음
- 드래그앤드랍 오류 수정을 위해 react-sortablejs 라이브러리를 react-beautiful-dnd로 대체하여 다시 구현함
=> Fix/#164 일정 편집 - 드래그 앤 드랍 오류 수정 및 Input, textarea 폰트크기 수정

.eslintrc.cjs, package-lock.json, src/assets/types/MyTravelItem.ts, src/components/common/Toast/Toast.tsx, src/components/common/Toast/style.ts, src/components/mytrip/LocationAddItem/index.tsx, src/components/tripDetail/LocationRecommendContents/index.tsx, src/hooks/useAlert/index.tsx, src/pages/PlacePage/index.tsx, src/pages/PlacePage/style.ts, src/pages/home/HomePage/index.tsx, src/pages/mytrip/DetailPage/index.tsx, src/pages/mytrip/DetailPage/style.ts, src/pages/mytrip/PlaceAddPage/index.tsx, src/router.tsx, src/styles/theme.ts, tsconfig.json
#179 
- 장소 페이지내 스낵바 삭제
- 토스트바 유지 시간 5초로 증가
- 장소 - 내 일정에 추가 UI 에서 다른 일정의 Day를 선택하여도 기존 선택이 지워지지 않는 문제
- 장소 검색 페이지의 “추가한 여행지를 포함한 콘텐츠 제공” → “제공” 빼기
- 여행 일정 상세보기 - 뒤로가기 버튼 추가
=> Feature/#179 UX 수정사항 반영

.eslintrc.cjs, src/assets/types/Button.type.ts, src/components/common/Button/FilledButton.tsx, src/components/common/Button/FilledButtons.style.ts, src/components/common/Button/button.style.ts, src/components/common/Button/default.style.ts, src/components/common/Header/Header.style.ts, src/components/common/Header/HeaderWithBack.tsx, src/components/common/Header/index.ts, src/components/cscenter/NavigationButtonContainer/index.tsx, src/components/cscenter/NavigationButtonContainer/style.ts, src/pages/cscenter/AnnounceDetailPage/index.tsx, src/pages/cscenter/AnnouncePage/index.tsx, src/pages/cscenter/CSCenterPage/index.tsx, src/pages/cscenter/FAQDetailPage/index.tsx, src/pages/cscenter/FeedBackPage/index.tsx, src/pages/cscenter/FeedBackPage/style.ts, src/pages/cscenter/InquiryDetailPage/index.tsx, src/pages/cscenter/InquiryHistoryPage/index.tsx, src/pages/cscenter/InquiryPage/index.tsx, src/pages/profile/ProfilePage/index.tsx, src/pages/profile/ProfilePage/style.ts, src/pages/profile/SettingsPage/index.tsx, src/pages/profile/SettingsPage/style.ts, src/pages/resign/ResignDonePage/index.tsx, src/pages/resign/ResignDonePage/style.ts, src/pages/resign/ResignPage/index.tsx, src/pages/resign/ResignPage/style.ts
#185 
- 환경설정 페이지 영역 내 UI 수정된 부분 반영
- Button > FilledButton 공통 컴포넌트 생성 및 반영
=> Feature/#185 환경설정 페이지 수정된 UI 반영

src/pages/auth/RedirectPage/index.tsx
=> feat(#209): social login test

index.html, package-lock.json, package.json, src/pages/auth/LoginPage/index.tsx
feat(#209): Apple Login 기본 설정 테스트
=> feat(#209): Apple Login 기본 설정 테스트

src/pages/auth/LoginPage/index.tsx
=> feat(#209): Apple Login Test

src/pages/auth/LoginPage/index.tsx
feat(#209): scope 및 response_mode 설정
=> feat(#209): scope 및 response_mode 설정

.github/workflows/main.yml, src/pages/auth/LoginPage/index.tsx
[apple Login ResponseMode Query 로 변경](https://github.com/F-orever/gabozago_FE/commit/4d69e57deae30e0ba4e051a0d6bff853680f8c9d)
=> apple Login ResponseMode Query 로 변경

src/pages/auth/LoginPage/index.tsx
[apple Login ResponseMode Query 로 변경](https://github.com/F-orever/gabozago_FE/commit/4d69e57deae30e0ba4e051a0d6bff853680f8c9d)
=> feat(#209): form_post 삭제

src/pages/auth/LoginPage/index.tsx
feat(#209): responseType & responseMode 설정
=> feat(#209): responseType & responseMode 설정

src/pages/auth/LoginPage/index.tsx
=> feat(#209): form_post 제거

src/pages/auth/LoginPage/index.tsx
feat(#209): Apple login logic 수정
=> feat(#209): Apple login logic 수정

src/pages/auth/LoginPage/index.tsx, src/pages/auth/RedirectPage/index.tsx
feat(#209): apple login Popup 추가
=> feat(#209): apple login Popup 추가

src/pages/auth/LoginPage/index.tsx, src/pages/auth/RedirectPage/index.tsx
feat(#209): Apple Login Code 백엔드까지 연결 테스트
=> feat(#209): Apple Login Code 백엔드까지 연결 테스트

src/pages/auth/LoginPage/index.tsx
=> feat(#209): syntax Error

src/pages/Auth/RedirectPage/index.tsx
=> feat(#209): 소셜 로그인 테스트

src/components/signUp/Nickname/index.tsx
=> feat(#209): 닉네임 검사시 token 추가

src/assets/types/LoginResponse.type.ts, src/components/signUp/Nickname/index.tsx, src/pages/Auth/RedirectPage/index.tsx
=> feat(#209): nickname 검사 로직 수정

src/pages/Auth/SignUpPage/index.tsx
feat(#209): Secure Cookie Test
=> feat(#209): Secure Cookie Test

src/pages/Auth/LoginPage/index.tsx
feat(#209): apple login acess_token 설정
=> feat(#209): apple login acess_token 설정

src/assets/types/LoginResponse.type.ts, src/components/signUp/Nickname/index.tsx, src/pages/Auth/LoginPage/index.tsx, src/pages/Auth/RedirectPage/index.tsx, src/pages/Auth/SignUpPage/index.tsx
=> Feature/#209 Social Login 기능 완성

src/components/common/isLoginTemplate.tsx, src/pages/Auth/LoginPage/index.tsx, src/pages/Auth/RedirectPage/index.tsx, src/pages/Auth/SignUpPage/index.tsx, src/pages/Home/index.tsx
Hotfix: Login Toast Message 설정, 브릿지 함수 실행 위치 조정
=> Hotfix: Login Toast Message 설정, 브릿지 함수 실행 위치 조정

src/assets/types/LoginResponse.type.ts, src/pages/Auth/LoginPage/index.tsx, src/pages/Auth/RedirectPage/index.tsx, src/pages/Auth/SignUpPage/index.tsx, src/pages/Profile/UserEditPage/index.tsx
=> fix: uuid 전송설정

src/pages/Auth/LoginPage/index.tsx, src/pages/Auth/RedirectPage/index.tsx, src/pages/Auth/SignUpPage/index.tsx, src/pages/Profile/UserEditPage/index.tsx
=> fix: testID 수정

src/pages/Auth/LoginPage/index.tsx, src/pages/Auth/RedirectPage/index.tsx
=> fix: 소셜로그인 에러 핸들링

src/pages/Auth/LoginPage/index.tsx, src/pages/Auth/RedirectPage/index.tsx
=> fix: Toast Design 수정

src/pages/Auth/LoginPage/index.tsx, src/pages/Auth/RedirectPage/index.tsx
=> fix: error toast 메시지 수정

vite.config.ts
=> fix: cache busting setting

src/pages/Home/index.tsx
=> fix: Cache Busting test

src/pages/Home/index.tsx
=> fix: Cache Busting Tets

src/pages/Auth/RedirectPage/index.tsx, src/pages/Home/index.tsx
=> fix: localStorage Test

src/pages/Auth/RedirectPage/index.tsx, src/pages/Home/index.tsx
[redirect URL 화면전환 안되는 문제 trouble shooting](https://github.com/F-orever/gabozago_FE/commit/54e269425a9bc9ff12ffd61f981af715cb1bda1a)
=> redirect URL 화면전환 안되는 문제 trouble shooting

src/components/common/PageTemplate/index.tsx, src/components/common/Toast/Toast/style.ts, src/components/post/BottomNav/index.tsx, src/pages/Auth/LoginPage/index.tsx, src/pages/Auth/LoginPage/style.ts, src/pages/Auth/RedirectPage/index.tsx, src/pages/Home/index.tsx, src/pages/Profile/UserEditPage/index.tsx
=> Apple 브릿지 에러 안되게 설정

src/components/common/isLoginTemplate.tsx, src/pages/Auth/LoginPage/index.tsx, src/pages/Auth/RedirectPage/index.tsx, src/pages/Profile/UserEditPage/index.tsx
=> fix: ios 브릿지 로직 수정

src/pages/Auth/LoginPage/index.tsx, src/pages/Auth/RedirectPage/index.tsx, src/pages/Profile/UserEditPage/index.tsx
fix: try-catch 구문 추가 -> 런타임 에러 방지
=> fix: try-catch 구문 추가 -> 런타임 에러 방지

src/pages/Home/index.tsx
=> fix: version update check

src/pages/Home/index.tsx
=> fix: callback test

src/pages/Home/index.tsx
=> fix: callback method test

src/pages/Home/index.tsx
=> fix: version up

src/pages/Auth/LoginPage/index.tsx, src/pages/Auth/RedirectPage/index.tsx, src/pages/Home/index.tsx, src/pages/Profile/UserEditPage/index.tsx
=> fix: ios 브릿지 코드 수정

src/pages/Auth/LoginPage/index.tsx, src/pages/Auth/RedirectPage/index.tsx, src/pages/Home/index.tsx
=> fix: android bridge test

index.html, src/components/common/BottomNavBar/index.tsx, src/components/common/PageTemplate/index.tsx, src/components/common/Toast/Toast/LoginToast.tsx, src/components/common/isLoginTemplate.tsx, src/components/home/HotArticles/index.tsx, src/components/post/BottomNav/index.tsx, src/components/signUp/Nickname/index.tsx, src/pages/Home/index.tsx, src/pages/Profile/Terms/index.tsx, src/router.tsx
#302
- 자세한 작업 내용은 notion QA 영역에 정리
=> Feature/#302 QA 수정사항 반영 로그인영역

src/components/home/HotArticles/index.tsx, src/pages/Profile/UserEditPage/index.tsx, src/pages/Scrap/ScrapContentPage/index.tsx
- 인기 급상승 아티클에 isScraped 반영
- 프로필 사진 바뀔 때 사진이 임의로 회전되는 에러
- 컨텐츠 스크랩 404 not found error 제어
=> Fix/#324 각종 에러 수정

src/components/common/isLoginTemplate.tsx, src/components/scrapBook/ScrapedTripPlace/index.tsx, src/components/scrapBook/ScrapedTripPlace/style.ts, src/pages/Profile/Terms/index.tsx, src/pages/Scrap/ScrapBookPlaceMapPage/index.tsx, src/pages/Scrap/ScrapContentPage/index.tsx, src/utils/isLocationTerms.ts
> #357
- 콘텐츠 상세보기 title 관련 수정
- kakao 로그인 실패 시, 잘못된 URL 로 return 되는 문제 해결
- 위치 권한 유무에 따른 로직 수정
- isLoginTemplate 수정 및 필요 path 로 반영
=> Feature/#357 각종 오류 개선

src/components/tripDetail/ScrapedPlace/index.tsx, src/components/tripDetail/ScrapedPlace/style.ts
=> 위치 권한 관련 설정 및 해당 팝업 표시

src/components/article/PlaceInfo/index.tsx, src/components/common/BottomNavBar/index.tsx, src/components/common/isLoginTemplate.tsx, src/components/journal/CommentItem/index.tsx, src/components/scrapBook/ScrapedTripJournal/index.tsx, src/hooks/useReportPopup/index.tsx, src/pages/Article/ArticlePage/index.tsx, src/pages/Home/index.tsx, src/pages/Mytrip/PlaceAddPage/index.tsx, src/pages/Mytrip/PlaceCreatePage/index.tsx, src/pages/Place/index.tsx, src/pages/PlaceMemoEditPage/index.tsx, src/pages/Profile/Terms/index.tsx, src/pages/Scrap/ContentMemoEditPage/index.tsx, src/pages/Scrap/ScrapBookPlaceMapPage/index.tsx, src/pages/Scrap/ScrapContentPage/index.tsx, src/utils/toastGenerate.tsx
#361 
-  스크랩 - 아티클 탭] 폴더 이름 수정 시, 화면에서 해당 폴더가 사라지는 문제와 함께... 다른 화면 갔다오면 해당 폴더 이름이 그대로 있음.
- 컨텐츠 스크랩 - 장소 스크랩] 작성된 메모가 없을 경우, 수정할 때 text box에서 null로 나타나는 문제
- 아티클 내 장소 카드 - 스크랩 아티클 내부의 장소카드에서 스크랩 버튼을 누르면, 스크랩 토스트바가 하나 띄워지는데... 첫 번째 토스트바가 화면에서 안사라지는 버그
- Footer 내 회사 이메일 정보 수정
=> Fix/#361 각종 오류 수정

package-lock.json, package.json, src/components/common/BottomNavBar/index.tsx, src/components/common/TabBar/index.tsx, src/components/common/filterInputs/Buttons/index.tsx, src/components/home/Banner/index.tsx, src/components/home/HotArticles/index.tsx, src/components/home/PlaceRecommendation/index.tsx, src/components/home/PopularArticles/index.tsx, src/components/profile/UserTrip/index.tsx, src/components/scrapBook/ScrapedContents/index.tsx, src/components/scrapBook/ScrapedTripPlace/index.tsx, src/components/tripDetail/DayPlan/index.tsx, src/components/tripDetail/TripPlanList/index.tsx, src/hooks/useMyTripModal/index.tsx, src/pages/Home/index.tsx, src/pages/Home/style.ts, src/pages/Mytrip/DetailPage/index.tsx, src/pages/Mytrip/MyTripPage/index.tsx, src/pages/Profile/ProfilePage/index.tsx, src/utils/GA4EventPush.ts
=> GA4 Event/Trigger 설정하기

src/pages/Profile/ProfilePage/index.tsx
=> feat(#363): MY 페이지 GA4 Event Push 설정

src/components/place/TripBucketContent/index.tsx, src/components/place/TripBucketContent/style.ts, src/components/scrapBook/NaverMap/index.tsx, src/pages/Mytrip/PlaceAddPage/index.tsx, src/pages/Place/index.tsx
> #373 
장소 상세 페이지내 기능 업데이트 및 버그 수정
=> Fix/#373 장소 상세 페이지내 기능 업데이트 및 버그 수정
